[package]
name = "diff"
version = "0.1.0"
authors = ["Adria Massanet <adria@codecontext.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.3"
anyhow = "1.0.32"

