[package]
name = "evmcodegen"
version = "0.1.0"
authors = ["adria0 <adria@codecontext.io>"]
edition = "2018"

[dependencies]

[dev-dependencies]
hex = "0.4.2"
web3 = "0.8.0"
easycontract = { git = "https://github.com/adria0/ethworkshop-rustfest" }
rustc-hex = "2.1.0"
hex-literal = "0.2.1" 